language: c

sudo: required
dist: trusty

before_install:
  - git clone --recursive https://github.com/brson/multirust && cd multirust
  - git submodule update --init
  - ./build.sh && sudo ./install.sh
  - multirust default 1.5.0
  - rustc --version
  - cd ..
  - uname -a
  - whoami
  - apt-get install golang
#  - wget https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz
#  - tar -C $HOME -xzf go1.5.2.linux-amd64.tar.gz
#  - export GOROOT=$HOME/go
#  - export PATH=$PATH:$GOROOT/bin
#  - export GOPATH=$GOROOT
#  - sudo apt-get install build-essentials

  # Haskell
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get install cabal-install-1.24 ghc-7.10.3
  - cabal update

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; cargo build)
  - (cd bankoconv; go build bankopladeformat2html.go)
  - (cd barc; cabal build)

script:
  - (cd bankopak; make test)
