language: c

sudo: required
dist: trusty

cache:
  apt: true
  directories:
    - multirust

before_install:
  # Rust
  - if [ ! -d multirust ]; then (git clone --recursive --depth 1 https://github.com/brson/multirust; cd multirust; git submodule update --init; ./build.sh); fi
  - ls multirust
  - sudo ./multirust/install.sh
  - multirust default 1.5.0
  - rustc --version

  # Haskell
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get -y install cabal-install-1.24 ghc-7.10.3
  - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.24/bin:$HOME/.cabal/bin:$PATH
  - cabal update
  - (cd barc; cabal install --only-dependencies)

  # Go
  - sudo apt-get -y install golang

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; make)
  - (cd bankoconv; make)
  - (cd barc; make)

script:
  - (cd bankopak; make test)
  - (cd barc/banko; make test)
