language: c

sudo: required
dist: trusty

before_install:
  # Rust
  - git clone --recursive https://github.com/brson/multirust && cd multirust
  - git submodule update --init
  - ./build.sh && sudo ./install.sh
  - multirust default 1.5.0
  - rustc --version
  - cd ..

  # Go
  - sudo apt-get update
  - sudo apt-get -y install golang

  # Haskell
  - sudo add-apt-repository -y ppa:hvr/ghc
  - sudo apt-get update
  - sudo apt-get -y install cabal-install-1.24 ghc-7.10.3
  - export PATH=/opt/ghc/7.10.3/bin:/opt/cabal/1.24/bin:$HOME/.cabal/bin:$PATH
  - cabal update

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; cargo build)
  - (cd bankoconv; go build bankopladeformat2html.go)
  - (cd barc; cabal configure && cabal build)

script:
  - (cd bankopak; make test)
