language: c

before_install:
  - sudo apt-get install golang
  - git clone --recursive https://github.com/brson/multirust && cd multirust
  - git submodule update --init
  - ./build.sh && sudo ./install.sh
  - multirust default 1.5.0
  - rustc --version
  - cd ..
#  - sudo apt-get install build-essentials

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; cargo build)
  - (cd bankoconv; go build bankopladeformat2html.go)

script:
  - (cd bankopak; make test)
