language: c

before_install:
  - git clone --recursive https://github.com/brson/multirust && cd multirust
  - git submodule update --init
  - ./build.sh && sudo ./install.sh
  - multirust default 1.5.0
  - rustc --version
  - cd ..
  - uname -a
#  - wget https://storage.googleapis.com/golang/go1.5.2.linux-amd64.tar.gz
#  - tar -C $HOME -xzf go1.5.2.linux-amd64.tar.gz
#  - export GOROOT=$HOME/go
#  - export PATH=$PATH:$GOROOT/bin
#  - export GOPATH=$GOROOT
   - apt install golang
   - sudo apt-get install golang
#  - sudo apt-get install build-essentials

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; cargo build)
  - (cd bankoconv; go build bankopladeformat2html.go)

script:
  - (cd bankopak; make test)
