language: minimal

sudo: required

dist: trusty

addons:
  apt:
    packages:
    - wget
    - libgmp-dev
    - libffi6
    - ocl-icd-libopencl1
    - opencl-headers

# cache:
  # directories:
    # - $HOME/.stack
    # - $TRAVIS_BUILD_DIR/barc/.stack-work
    # - multirust
  # timeout: 300

before_install:
  # Rust
  - (if [ ! -d multirust ]; then git clone --recursive --depth 1 https://github.com/brson/multirust; cd multirust; git submodule update --init; ./build.sh; fi)
  - (cd multirust; sudo ./install.sh)
  - multirust default 1.26.0
  - rustc --version

  # # Haskell
  # - export PATH=$HOME/.local/bin:$PATH
  # - mkdir -p ~/.local/bin
  # - curl -sL https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack';
  # - stack --no-terminal setup --verbose
  # - (cd barc; stack build --fast)

  # install Futhark
  - wget http://futhark-lang.org/releases/futhark-nightly-linux-x86_64.tar.xz
  - tar xf futhark-nightly-linux-x86_64.tar.xz
  - (cd futhark-nightly-linux-x86_64/ && PREFIX=$HOME/.local make install)

  # Go
  - sudo apt-get -y install golang

install:
  - pwd
  - ls
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; make)
  - (cd bankoconv; make)
  # - (cd barc; stack build --fast)
  - (cd futbankosim; make)

script:
  - (cd bankopak; make test)
  # - (cd barc; stack install)
  # - (cd barc/banko; make test)
