language: rust

before_install:
  - sudo apt-get install build-essentials

install:
  - (cd bankopladeformat; make)
  - (cd bankopak; make)
  - (cd bankoviser; cargo build)

script:
  - (cd bankopak; make test)
