name: bankotrav
synopsis: A banko card traverser

ghc-options: -Wall -O3

dependencies:
  - base >= 4 && < 5
  - containers >= 0.5
  - mtl >= 2.2.1
  - safe >= 0.2
  - random >= 1.1
  - random-fu >= 0.2.5.0
  - MonadRandom >= 0.5.1

library:
  source-dirs: src

executables:
  bankotrav: &bankotrav
    main: src/bankotrav.hs
    dependencies:
      - bankotrav
